Add Style for main
Milardez/MAMAKUPI pull request #2
Opened 2018-09-13 08:31 UTC by Milardez

2018-09-13 18:12 UTC, Afelua requested changes

2018-09-13 18:12 UTC, Afelua commented on style.css
> + .backround-image { background-image: url("images/background.jpg");
Синтаксическая ошибка, класс в HTML называется .background-image, из-за этого картинка не грузится.

2018-09-13 18:12 UTC, Afelua commented on style.css
> +width: 400px;
Слишком маленькое значение, этот элемент включает белый квадрат 394px и картинку. Из-за этого белый квадрат не показывается (он не влезает).

2018-09-13 18:12 UTC, Afelua commented on style.css
> +  width: 500px;
Тоже 500 - слишком мало, здесь больше 1000

2018-09-13 18:12 UTC, Afelua commented on style.css
> +.container {
Стоит также указать отступы для внутреннего содержимого, padding

2018-09-13 18:12 UTC, Afelua commented on style.css
> +color:#fd634e;
Здесь зеленый цвет по макету
<img width="268" alt="screen shot 2018-09-13 at 21 08 24" src="https://user-images.githubusercontent.com/8777546/45506873-2d23cb80-b799-11e8-813a-35e929d85a0e.png">

2018-09-13 18:12 UTC, Afelua commented on index.html
> +			<h3 class="h3 -class2"> Love Your</h3>
Неверные синтаксис, поставлен лишний пробел, должно быть h3-class2

2018-09-13 18:12 UTC, Afelua commented on index.html
> +			<h3 class="h3 -class2"> Love Your</h3>
Для элементов ниже не указаны классы.

2018-09-13 18:12 UTC, Afelua commented on style.css
> +.section2 {
Если элементы ведут себя одинаково, то должны быть одинаковые классы. Нет смысла создавать два класса (.section2 и .section) с едиными стилями.

2018-09-13 18:12 UTC, Afelua commented on style.css
> +	color: #fd634e;
Здесь заглавные буквы (text-transform: uppercase;)

2018-09-13 18:12 UTC, Afelua commented on style.css
> +.section2 {
Проверить везде.

2018-09-13 18:12 UTC, Afelua commented on style.css
> +.container {
Также выравнить содержимое по центру:     text-align: center;

2018-09-13 18:12 UTC, Afelua commented on style.css
> +justify-content: space-around;
Здесь space-around; задавать не надо.

2018-09-16 09:34 UTC, Milardez commented on style.css
> + .backround-image { background-image: url("images/background.jpg");
<header class=".background-image"> -перед названием класса в индексе надо точку поставить? )
в css стоит точка как положено

2018-09-17 09:17 UTC, Milardez commented on style.css
> + .backround-image { background-image: url("images/background.jpg");
исправила

2018-09-17 10:23 UTC, Milardez commented on style.css
> +	color: #fd634e;
исправила

2018-09-17 20:02 UTC, Afelua requested changes

2018-09-17 20:02 UTC, Afelua commented on style.css
> + 	color: #ffffff
Здесь съехали стили. Нужно обязательно ставить ; после каждой строки.

2018-09-17 20:02 UTC, Afelua commented on style.css
> +.section {
Стоит написать margin: 0 auto, чтобы блок встал по центру (было на предыдущем стриме).

2018-09-17 20:02 UTC, Afelua commented on style.css
> +	height:399px;
Лучше не ограничивать высоту, чтобы блок подстраивался под размер картинки, а не наоборот.

<img width="1235" alt="screen shot 2018-09-17 at 22 59 46" src="https://user-images.githubusercontent.com/8777546/45646973-65931480-bacd-11e8-9bb8-f595c8b4f056.png">

2018-09-17 20:02 UTC, Afelua commented on style.css
> +.icon5-class {
Не нужно оставлять пустые классы.

2018-09-17 20:02 UTC, Afelua commented on style.css
> +	height:399px;
Чтобы капелька встала по центру, нужно написать text-align: center; для .square (родительский класс для капельки).

2018-09-17 20:02 UTC, Afelua commented on style.css
> +.section2 {
Если стили те же самые, то и класс должен называться также (.section).

2018-09-17 20:02 UTC, Afelua commented on style.css
> +.section2 {
Проверить везде.

2018-09-17 20:02 UTC, Afelua commented on style.css
> +height: 1000px;
1000 - слишком много, поэтому отображается белый отступ.

<img width="1230" alt="screen shot 2018-09-17 at 23 02 21" src="https://user-images.githubusercontent.com/8777546/45647121-c15d9d80-bacd-11e8-925a-3162322b93eb.png">

2018-09-18 08:30 UTC, Milardez commented on style.css
> + 	color: #ffffff
исправлено

2018-09-18 08:34 UTC, Milardez commented on style.css
> +.section {
спасибо, надо пересмотреть еще раз.

2018-09-18 08:38 UTC, Milardez commented on style.css
> +.icon5-class {
ок

2018-09-18 08:42 UTC, Milardez commented on style.css
> +height: 1000px;
поставила 800, маленький отступ все равно остался, но если ставить меньше картинкам сама меньше становится и все съезжает.

2018-09-18 08:48 UTC, Milardez commented on style.css
> +.section2 {
сделано

2018-09-18 17:33 UTC, Afelua commented on style.css
> + .backround-image { background-image: url("images/background.jpg");
Точки перед классами ставятся только в CSS-файле.

2018-09-18 17:35 UTC, Afelua approved these changes

2018-09-19 10:51 UTC, merged