Task 6
Milardez/MAMAKUPI pull request #3
Opened 2018-09-21 12:20 UTC by Milardez

2018-09-21 22:38 UTC, Afelua requested changes

2018-09-21 22:38 UTC, Afelua commented on style.css
>     margin: 400px 100px 0 0;
Нужен отступ слева для title.

2018-09-21 22:38 UTC, Afelua commented on index.html
> +				<p class="block-text">  Easly manage your inspiration and work-in-progress  by dragging images into projects and sharable client groups. Easily manage your inspiration and</p>
Нужно задать отступ сверху для этого списка, по макету он есть.

2018-09-21 22:38 UTC, Afelua commented on style.css
> +    border: 1px, solid gray;
Таким образом стили не сработают, запятую после 1px ставить не надо.

2018-09-21 22:38 UTC, Afelua commented on style.css
> +	color:gray;
Проверить цвет по макету, задать в HEX, он не серый.  Также нужно прописать размер шрифта и сам шрифт.

2018-09-21 22:38 UTC, Afelua commented on style.css
> +	background: #a2ca28;
Прописать размер шрифта и сам шрифт.

2018-09-21 22:38 UTC, Afelua commented on style.css
> +.hover: before {
Синтаксическая ошибка, псевдоэлемент пишется без пробела:
.hover:before

2018-09-21 22:38 UTC, Afelua commented on index.html
> +		 <div class="text-hover">
Элемент с текстом text-hover должен быть внутри hover

2018-09-21 22:38 UTC, Afelua commented on index.html
> +		 <div class="text-hover">
Также нужно стилизовать сам текст (размеры шрифта, цвет и др.)

2018-09-21 22:38 UTC, Afelua commented on style.css
>     padding: 50px 40px 80px 40px;
Очень большой padding снизу, из-за этого отступ под картинкой:
<img width="1174" alt="screen shot 2018-09-22 at 01 35 32" src="https://user-images.githubusercontent.com/8777546/45908933-d016be00-be07-11e8-94ab-fb95a9fbd117.png">

2018-09-24 10:54 UTC, Milardez commented on index.html
> +		 <div class="text-hover">
ипсравлено

2018-09-24 10:54 UTC, Milardez commented on style.css
> +.hover: before {
ок

2018-09-24 10:54 UTC, Milardez commented on style.css
> +	background: #a2ca28;
ок

2018-09-24 10:54 UTC, Milardez commented on style.css
> +	color:gray;
сделано

2018-09-24 10:54 UTC, Milardez commented on style.css
> +    border: 1px, solid gray;
ясно

2018-09-24 11:09 UTC, Milardez commented on style.css
>     padding: 50px 40px 80px 40px;
исправила, но маленький отступ все равно остается

2018-09-24 11:11 UTC, Milardez commented on index.html
> +				<p class="block-text">  Easly manage your inspiration and work-in-progress  by dragging images into projects and sharable client groups. Easily manage your inspiration and</p>
не понимаю как сделать, поясните пожалуйста

2018-09-24 11:11 UTC, Milardez commented on style.css
>     margin: 400px 100px 0 0;
ок

2018-09-24 22:46 UTC, Afelua requested changes

2018-09-24 22:46 UTC, Afelua commented on index.html
> +
В 6-ом дз нужно сбросить стили по умолчанию - http://elenasemenova.ru/mcs/lesson6/assets/player/KeynoteDHTMLPlayer.html#16 (см. пример с урока).

2018-09-24 22:46 UTC, Afelua commented on index.html
> +				<p class="block-text">  Easly manage your inspiration and work-in-progress  by dragging images into projects and sharable client groups. Easily manage your inspiration and</p>
Не хватает padding сверху и снизу для элемента main-menu, например, padding: 40px 0;

2018-09-24 22:46 UTC, Afelua commented on style.css
>     margin: 400px 100px 0 0;
Отступ сейчас оказался справа, а слева его нет(
<img width="509" alt="screen shot 2018-09-25 at 01 29 40" src="https://user-images.githubusercontent.com/8777546/45982716-7eb63b00-c062-11e8-8e5f-2821728d6e36.png">

2018-09-24 22:46 UTC, Afelua commented on style.css
> +    text-align: center;
text-align: center; срабатывает только для родительского элемента (т.е., чтобы отразилось на его дочерним, нужно присваивать родительскому); здесь это свойство бессмысленно. Но могло бы сработать, если бы  вы присвоили класс внешнему div:

```
<div>
<h3 class="text-hoverh3"> It's all about </h3>
h2 class="text-hoverh2"> Fitness First </h2>
</div>
```

и указали text-align: center для него.

2018-09-24 22:46 UTC, Afelua commented on style.css
> +.hover {
Стоит ограничить высоту блока hover, чтобы не было зеленый полосы внизу (подобрать актуальное значение):

<img width="1219" alt="screen shot 2018-09-25 at 01 38 37" src="https://user-images.githubusercontent.com/8777546/45983053-bd002a00-c063-11e8-8b0e-fccad2bb22c7.png">

2018-09-24 22:46 UTC, Afelua commented on style.css
> +    width: 700px;
700px - слишком маленькое значение, нужно указать около 900.

2018-09-24 22:46 UTC, Afelua commented on style.css
> + width: 100px;
Форма отображается некорректно за счет этих характеристик.

Свойства 
`    width: 100px;
    display: flex;
    justify-content: space-between;`

не нужны, и их надо удалить. Во-первых, слишком маленькая ширина всей формы .form (она стоит в 100 пикселей, хотя на деле около 400); во-вторых, элементы формы встают в 1 ряд по умолчанию, и нет смысла писать для них `    display: flex;
    justify-content: space-between;`

Но margin нужно задать актуальный (на одном уровне с иконками соц. сетей).

2018-09-24 22:46 UTC, Afelua commented on style.css
> +.text-hoverYB {
CSS-свойства этого элемента такие же, как у text-hoverh2, - значит, это - должен быть один и тот же класс.  С классами text-hoverh3 и text-hoverLY аналогично. 

Выравнивать тексты именно по середине мы будем на 7-ом уроке)

2018-09-25 08:43 UTC, Milardez commented on index.html
> +				<p class="block-text">  Easly manage your inspiration and work-in-progress  by dragging images into projects and sharable client groups. Easily manage your inspiration and</p>
Спасибо, я забыла про этот класс и что он родительский, поэтому не понимала где отступ писать.

2018-09-25 08:45 UTC, Milardez commented on style.css
> +    text-align: center;
спасибо, была какая то мысль на счет бесполезности text align в аднном случае, но не могла понять почему. выроаняла с помощью left right

2018-09-25 08:46 UTC, Milardez commented on index.html
> +
вроде применила в предыдущих комитах.
 там есть Add normalize reset

2018-09-25 09:08 UTC, Milardez commented on style.css
> + width: 100px;
Спасибо, получилось!

2018-09-25 09:13 UTC, Milardez commented on style.css
> +.text-hoverYB {
там заголовок h3 love your- стоит над h2- Your body- а в верхней секции наоборот
Как в одном и том же стиле прописать разное положение заголовков?
я не поняла, поэтому сделала доп классы.

2018-09-25 09:16 UTC, Milardez commented on style.css
>     margin: 400px 100px 0 0;
исправила.

2018-09-25 09:19 UTC, Milardez commented on style.css
> +.hover {
поставила свойство height 400 px (такая же как у фона затемнения) в класс .hover -все поехало.
не могу понять проблему.

2018-09-25 10:43 UTC, Milardez commented on index.html
> +
добавила в index

2018-09-25 23:30 UTC, Afelua commented on style.css
> +.hover {
400px (а, точнее, 394px) нужно ставить для класса .hover. Для before - аналогичное значение.

2018-09-25 23:33 UTC, Afelua commented on style.css
> +.text-hoverYB {
Друг под другом заголовки находятся или нет никак не влияет на стилизацию элементов, все равно у них должны быть одни и те же классы. И все, что связано с позионированием, мы в эти классы не включает (только шрифт, цвет и др.). 

Все, что связано с позицонированием ( position: absolute; left, top ) нужно писать для класса hover-title

2018-09-25 23:36 UTC, Afelua requested changes

2018-09-25 23:36 UTC, Afelua commented on style.css
> +}
Не заданы размеры шрифтов и отступы для этих блоков:

<img width="376" alt="screen shot 2018-09-26 at 02 35 14" src="https://user-images.githubusercontent.com/8777546/46049004-d45b1800-c134-11e8-9048-e1d6db0075a3.png">

2018-09-25 23:36 UTC, Afelua commented on style.css
> +  top: 20px;
Отступы сверху задаем через padding или margin, здесь top не имеет смысла (тем более, что без position: absolute он вовсе не сработает).

2018-09-26 10:16 UTC, Milardez commented on style.css
> +.hover {
сработало, спасибо)

2018-09-26 10:30 UTC, Milardez commented on style.css
> +.text-hoverYB {
вот я пишу для hover -title настройки позиционирования,
 но получается что оба класса h3- будут с одинаковым показателем top, а он у них разный по макету. тоже самое с положением h2. Как это можно прописать в одном классе?

2018-09-26 10:43 UTC, Milardez commented on style.css
> +}
padding задала.
размер шрифта прописан в классе .block, неверно?

.block
  {
  display: flex;
  list-style: none;
  width: 1150px;
  justify-content: space-around;
  color: #ffffff;
  font-size: 14px;
  margin: 0 auto;
 }

2018-09-26 10:44 UTC, Milardez commented on style.css
> +  top: 20px;
это я уже поняла)

2018-09-26 11:40 UTC, Afelua commented on style.css
> +}
Да, нужно шрифт прописывать для каждого отдельного класса внутри .block, т.к. шрифт везде разный.

2018-09-28 07:22 UTC, Afelua requested changes

2018-09-28 07:22 UTC, Afelua commented on style.css
> +    font-weight:300;
Не прописан размер шрифта (сколько пикселей), также нужен padding или margin для отступа сверху.

2018-09-28 07:22 UTC, Afelua commented on style.css
> +	font-weight:100;
Прописать padding сверху для отступа от пред элемента.

2018-09-28 07:22 UTC, Afelua commented on index.html
> +			 <img src="images/icon5.svg" height="50">
Прописать padding сверху для отступа от пред элемента.

2018-09-28 07:22 UTC, Afelua commented on style.css
> +
Прописать padding сверху для отступа от пред элемента.

2018-09-28 07:22 UTC, Afelua commented on style.css
> +	background: #a2ca28;
Кнопка по высоте должна быть такого же размера, как инпуты (подогнать padding).

2018-09-28 11:23 UTC, Milardez commented on style.css
> +	font-weight:100;
добавила

2018-09-28 11:23 UTC, Milardez commented on index.html
> +			 <img src="images/icon5.svg" height="50">
добавила

2018-09-28 11:28 UTC, Milardez commented on style.css
> +
добавила

2018-09-28 12:26 UTC, Milardez commented
исправила

2018-09-29 18:45 UTC, Afelua approved these changes

2018-10-01 08:09 UTC, merged