Task 7
Milardez/MAMAKUPI pull request #4
Opened 2018-10-05 13:07 UTC by Milardez

2018-10-06 08:35 UTC, Afelua requested changes

2018-10-06 08:35 UTC, Afelua commented on index.html
>  			<ul class="block">
Высота главной картинки должна быть больше по макету.
<img width="1045" alt="screenshot 2018-10-06 at 11 22 28" src="https://user-images.githubusercontent.com/8777546/46569212-46640600-c95a-11e8-985f-a90486954ca1.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
Также нужно задать больший padding сверху для .main-menu
<img width="1193" alt="screenshot 2018-10-06 at 11 23 13" src="https://user-images.githubusercontent.com/8777546/46569217-50860480-c95a-11e8-962a-cbc2b56d92f8.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
Padding для .block-subtitle нужно отрегулировать.

<img width="310" alt="screenshot 2018-10-06 at 11 24 39" src="https://user-images.githubusercontent.com/8777546/46569229-727f8700-c95a-11e8-9e64-1f9121f9aa1e.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
По ссылкам - у вас синтаксическая ошибка, нужно удалить } на 156-ой строке.
<img width="640" alt="screenshot 2018-10-06 at 11 32 34" src="https://user-images.githubusercontent.com/8777546/46569311-8972a900-c95b-11e8-8d28-39eef6dfb184.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
Также для .main-menu нужен отступ снизу, чтобы картинка наложилась по макету. 
<img width="1245" alt="screenshot 2018-10-06 at 11 25 59" src="https://user-images.githubusercontent.com/8777546/46569241-ace92400-c95a-11e8-84bf-163ece109b9b.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> +			<li> <div class="block-image_container">
Здесь требуется прописать актуальные padding для .square, .h3-class, .h2-class, задать правильную высоту иконки капли, отступ снизу .text-class .
<img width="465" alt="screenshot 2018-10-06 at 11 27 54" src="https://user-images.githubusercontent.com/8777546/46569248-e3bf3a00-c95a-11e8-931c-cba174f69cdb.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> +			 <img  src="images/icon5.svg" height="50">
Для .footer-container нужен отступ слева согласно макету.
Также требуется задать актуальный отступ сверху.
<img width="1237" alt="screenshot 2018-10-06 at 11 29 09" src="https://user-images.githubusercontent.com/8777546/46569260-0ea98e00-c95b-11e8-9324-7d9f934552d2.png">

2018-10-06 08:35 UTC, Afelua commented on index.html
> -
Все содержимое формы тоже должно накладываться. Нужно задать актуальные padding и width для .input и для кнопки.

2018-10-06 08:35 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
По анимации - тоже синтаксическая ошибка, scale(1) должно быть написано слитно, а не через пробел scale (1) . Также нужно, чтобы сама анимация происходила при наведении.

2018-10-08 09:47 UTC, Milardez commented on index.html
>  			<ul class="block">
сделала 900 px

2018-10-08 10:23 UTC, Milardez commented on index.html
> -				<img src="images/icon1.svg" alt="">
поправила, анимация заработала , но ссылки уезжают влево) я хотела добиться эффекта пульсации) надо видимо как то поменять по осям)

2018-10-08 10:45 UTC, Milardez commented on index.html
> +			<li> <div class="block-image_container">
поменяла

2018-10-08 13:24 UTC, Milardez commented on index.html
> -				<img src="images/icon1.svg" alt="">
синтаксис исправила

2018-10-08 14:04 UTC, Milardez commented on index.html
> +			 <img  src="images/icon5.svg" height="50">
исправила

2018-10-08 20:26 UTC, Milardez commented on index.html
> +			 <img  src="images/icon5.svg" height="50">
поправила

2018-10-09 12:09 UTC, Afelua requested changes

2018-10-09 12:09 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
По .main-menu - отступ пока еще не актуален. Должно накладываться.

<img width="1170" alt="screenshot 2018-10-09 at 14 44 01" src="https://user-images.githubusercontent.com/8777546/46667265-cd6ee380-cbd1-11e8-97e2-fa946407f2f8.png">

2018-10-09 12:09 UTC, Afelua commented on index.html
> -				<img src="images/icon1.svg" alt="">
Также этот коммент актуален.

<img width="761" alt="screenshot 2018-10-09 at 14 47 01" src="https://user-images.githubusercontent.com/8777546/46667397-3f472d00-cbd2-11e8-9d31-f7713afae19c.png">

2018-10-09 12:09 UTC, Afelua commented on style.css
> +     animation: Block-LinkAnimation 3s infinite;
Анимацию лучше создать для состояния hover, а не для всех.

2018-10-09 12:09 UTC, Afelua commented on style.css
> +
Если интересует эффект пульсации, то есть еще scale3d. Подробная инструкция описана здесь https://elena-koreibo.ru/design/effekt-pulsaczii-pulsehtml

2018-10-09 12:09 UTC, Afelua commented on index.html
> +			<li> <div class="block-image_container">
До сих пор не накладывается, в т.ч. для .h3-class размер шрифта неактуальный.

2018-10-09 12:09 UTC, Afelua commented on index.html
> +			<li> <div class="block-image_container">
Особое внимание стоит уделить .text-class. 

<img width="449" alt="screenshot 2018-10-09 at 14 59 27" src="https://user-images.githubusercontent.com/8777546/46668008-f09a9280-cbd3-11e8-8887-b33790ac2a4e.png">

2018-10-09 12:09 UTC, Afelua commented on index.html
> -
Стоит проверить padding у инпутов.

<img width="445" alt="screenshot 2018-10-09 at 15 00 24" src="https://user-images.githubusercontent.com/8777546/46668060-1889f600-cbd4-11e8-88c2-119d40d8948a.png">

Также нужно прописать ширину для второго инпута, по макету он больше.

2018-10-09 12:09 UTC, Afelua commented on style.css
> + 	width: 25px;
Размеры иконок нужно задать актуальные (ширину и высоту), сейчас не накладывается. 

<img width="300" alt="screenshot 2018-10-09 at 15 08 21" src="https://user-images.githubusercontent.com/8777546/46668467-2f7d1800-cbd5-11e8-850e-44a1046f9f60.png">

2018-10-12 13:01 UTC, Milardez commented on index.html
> -				<img src="images/icon1.svg" alt="">
resources наложился остальные все равно немного съезжают.

2018-10-12 13:19 UTC, Milardez commented on index.html
> +			<li> <div class="block-image_container">
для h3 класс перепроверила там Montserrat 14 px в макете показывает.
поправила text class подогнала width для .section  Капелька все равно съезжает.
ссылка Read Me почему то не двигается...

2018-10-17 12:23 UTC, Milardez commented on index.html
> -
ок

2018-10-19 14:55 UTC, Afelua requested changes

2018-10-19 14:55 UTC, Afelua commented on index.html
> +			<li> <div class="block-image_container">
Нужно задать больший padding снизу для класса .h2-class и меньший padding сверху для .text-class.

2018-10-19 14:55 UTC, Afelua commented on index.html
> +			<li> <div class="block-image_container">
Также, чтобы выровнить Read more, нужно задать меньший padding снизу для .text-class

2018-10-19 14:55 UTC, Afelua commented on style.css
> + 	width: 25px;
Нужно доделать, например, fb не 25px, надо подогнать под макет.

2018-10-21 13:47 UTC, Milardez commented on index.html
> +			<li> <div class="block-image_container">
поправила

2018-10-21 14:06 UTC, Milardez commented
у меня было 50
стала менять иконки задублировались.

2018-10-25 09:55 UTC, Afelua approved these changes

2018-10-25 09:55 UTC, Afelua commented on style.css
> +
Чтобы анимация срабатывала только при ховер, нужно удалить

.pulse {
  animation: pulse-BlockLinkAnimation 3s infinite;} - эта строка означает, что анимация будет срабатывать всегда.


В этой строке
  .block-link.pulse:hover { 
  	animation: pulse-BlockLinkAnimation 3s infinite; }

пишем просто:
.pulse:hover { 
  	animation: pulse-BlockLinkAnimation 3s infinite; }

2018-10-25 11:59 UTC, Milardez commented
поняла, спасибо.

2018-10-25 12:04 UTC, merged